version: 2.1

jobs:
  scan:
    docker:
      - image: alpine:3.12
        environment:
          CC: clang

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: apk add --no-cache --update alpine-sdk automake autoconf clang clang-analyzer glib-dev libtool

      - run:
          name: Setup build
          command: |
            autoreconf -i -f
            ./configure

      - run:
          name: Scan build
          command: scan-build --status-bugs -o /tmp/mausbery-switch make

      - store_artifacts:
          path: /tmp/mausbery-switch

workflows:
  main:
    jobs:
      - build
      - test
      - lint
      - scan
