version: 2.1
jobs:
  build:
    docker:
      - image: debian:buster
        environment:
          CFLAGS: -O2 -pipe -fstack-protector-strong -fno-plt
          CPPFLAGS: -D_FORTIFY_SOURCE=2
          DEBIAN_FRONTEND: noninteractive
          LDFLAGS: -Wl,-O1,--sort-common,--as-needed,-z,relro
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG_PATH: /usr/lib/arm-linux-gnueabihf/pkgconfig/

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            dpkg --add-architecture armhf
            apt-get update -q
            apt-get install -qy crossbuild-essential-armhf dh-autoreconf libglib2.0-dev:armhf ruby ruby-dev

      - run:
          name: Create install directory
          command: mkdir -p /tmp/installdir

      - run:
          name: Install fpm
          command: gem install --no-document fpm

      - run:
          name: Autoreconf
          command: autoreconf -i -f

      - run:
          name: Configure
          command: ./configure --prefix=/usr --sysconfdir=/etc --build=x86_64-linux-gnu --host=arm-linux-gnueabihf

      - run:
          name: Make
          command: make

      - run:
          name: Make install
          command: make DESTDIR=/tmp/installdir install-strip

      - run:
          name: Build debian package
          command: |
            fpm \
              -f \
              -s dir \
              -t deb \
              -n mausberry-switch \
              -v 0.8 \
              -C /tmp/installdir \
              -p mausberry-switch_VERSION_armhf.deb \
              -d "libglib2.0-0 >= 2.42" \
              --deb-systemd data/mausberry-switch.service \
              usr/bin etc

      - run:
          name: Inspect package contents
          command: |
            ar x mausberry-switch_*.deb
            tar tvf data.tar.gz

      - store_artifacts:
          path: mausberry-switch_*.deb
